"""
Corrections routes — agronomist feedback loop.

POST /api/v1/corrections/                    → submit a correction on an evidence edge
GET  /api/v1/corrections/                    → list corrections (admin/agronomist)
POST /api/v1/corrections/{id}/confirm-edge   → confirm a causal edge (CONFIRMED_CAUSE)
POST /api/v1/corrections/trigger-memify      → manually trigger memify batch (admin)

Every correction:
  1. Is stored in Postgres with the correcting user's ID and timestamp
  2. Queues a memify() Celery task (if batch hasn't already run today)
  3. Invalidates the Redis query cache for the farm
  4. Is included in the nightly evaluation log
"""

import structlog
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from app.core.auth import TokenData, require_role
from app.core.database import get_db
from app.core.neo4j_client import mark_edge_confirmed
from app.core.redis_client import invalidate_query_cache
from app.models.db import Correction, EvidenceEdge, QueryLog
from app.models.schemas import CorrectionCreate, CorrectionRead

log = structlog.get_logger(__name__)
router = APIRouter()


@router.post("/", response_model=CorrectionRead, status_code=201)
async def submit_correction(
    body: CorrectionCreate,
    td: TokenData = Depends(require_role("admin", "agronomist")),
    db: AsyncSession = Depends(get_db),
):
    # Verify the evidence edge belongs to this farm
    result = await db.execute(
        select(EvidenceEdge)
        .join(EvidenceEdge.query)
        .where(
            EvidenceEdge.id == body.evidence_edge_id,
            QueryLog.farm_id == td.farm_id,
        )
    )
    edge = result.scalar_one_or_none()
    if not edge:
        raise HTTPException(status_code=404, detail="Evidence edge not found")

    correction = Correction(
        evidence_edge_id=body.evidence_edge_id,
        corrected_by_user_id=td.user_id,
        correction_note=body.correction_note,
        memify_queued=False,
    )
    db.add(correction)
    await db.flush()

    # Invalidate query cache so future queries reflect the correction
    n_invalidated = await invalidate_query_cache(td.farm_id)
    log.info(
        "correction.submitted",
        correction_id=correction.id,
        edge_id=body.evidence_edge_id,
        user=td.user_id,
        cache_keys_invalidated=n_invalidated,
    )

    # Dispatch memify task for this farm
    _dispatch_memify(td.farm_id)

    return correction


@router.get("/", response_model=list[CorrectionRead])
async def list_corrections(
    td: TokenData = Depends(require_role("admin", "agronomist")),
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(Correction)
        .join(EvidenceEdge, EvidenceEdge.id == Correction.evidence_edge_id)
        .join(EvidenceEdge.query)
        .where(QueryLog.farm_id == td.farm_id)
        .order_by(Correction.created_at.desc())  # type: ignore[attr-defined]
        .limit(100)
    )
    return result.scalars().all()


@router.post("/{correction_id}/confirm-edge")
async def confirm_causal_edge(
    correction_id: str,
    td: TokenData = Depends(require_role("admin", "agronomist")),
    db: AsyncSession = Depends(get_db),
):
    """
    An agronomist explicitly confirms that an edge represents a confirmed cause.
    This promotes the Neo4j edge to CONFIRMED_CAUSE type (the only way this
    edge type is ever asserted — never auto-generated by the LLM).
    """
    result = await db.execute(
        select(Correction, EvidenceEdge)
        .join(EvidenceEdge, EvidenceEdge.id == Correction.evidence_edge_id)
        .join(EvidenceEdge.query)
        .where(Correction.id == correction_id, QueryLog.farm_id == td.farm_id)
    )
    row = result.one_or_none()
    if not row:
        raise HTTPException(status_code=404, detail="Correction not found")

    correction, edge = row
    await mark_edge_confirmed(
        source_id=edge.graph_node_id,
        target_id="",  # Neo4j looks up by node ID
        rel_type=edge.relationship_type,
        confirmed_by=td.user_id,
    )
    log.info("correction.edge_confirmed", edge_id=edge.id, agronomist=td.user_id)
    return {"detail": "Edge confirmed as causal", "edge_id": edge.id}


@router.post("/trigger-memify", status_code=202)
async def trigger_memify(
    td: TokenData = Depends(require_role("admin")),
):
    """Manually trigger a memify batch for the authenticated farm."""
    _dispatch_memify(td.farm_id)
    log.info("correction.memify_triggered", farm_id=td.farm_id, user=td.user_id)
    return {"detail": "Memify batch queued", "farm_id": td.farm_id}


def _dispatch_memify(farm_id: str) -> None:
    from app.workers.celery_app import celery_app
    celery_app.send_task(
        "app.workers.tasks.run_memify_batch",
        kwargs={"farm_id": farm_id},
        queue="memify",
    )
