"""
Corrections routes — agronomist feedback loop.

POST /api/v1/corrections/                    → save a correction on an evidence edge
GET  /api/v1/corrections/                    → list corrections (admin/agronomist)
POST /api/v1/corrections/{id}/confirm-edge   → confirm a scoped correlation with both graph endpoints
POST /api/v1/corrections/trigger-memify      → retry saved corrections that are not queued

Every correction:
  1. Is stored in Postgres with the correcting user's ID and timestamp
  2. Invalidates the Redis query cache for the farm
  3. Queues Cognee's supported memify operation for the correction's plot dataset
"""

import structlog
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from app.core.auth import TokenData, require_role
from app.core.database import get_db
from app.core.neo4j_client import mark_edge_confirmed
from app.core.redis_client import invalidate_query_cache
from app.models.db import Correction, EvidenceEdge, QueryLog
from app.workers.tasks import memify_correction
from app.models.schemas import CorrectionCreate, CorrectionRead

log = structlog.get_logger(__name__)
router = APIRouter()


@router.post("/", response_model=CorrectionRead, status_code=201)
async def submit_correction(
    body: CorrectionCreate,
    td: TokenData = Depends(require_role("admin", "agronomist")),
    db: AsyncSession = Depends(get_db),
):
    # Verify the evidence edge belongs to this farm
    result = await db.execute(
        select(EvidenceEdge, QueryLog)
        .join(EvidenceEdge.query)
        .where(
            EvidenceEdge.id == body.evidence_edge_id,
            QueryLog.farm_id == td.farm_id,
        )
    )
    row = result.one_or_none()
    if not row:
        raise HTTPException(status_code=404, detail="Evidence edge not found")
    edge, query = row

    correction = Correction(
        evidence_edge_id=body.evidence_edge_id,
        corrected_by_user_id=td.user_id,
        correction_note=body.correction_note,
        memify_queued=False,
    )
    db.add(correction)
    await db.flush()
    await db.commit()

    # Queue only after the correction is durable, so a fast worker can read it.
    try:
        memify_correction.apply_async(args=[correction.id, td.farm_id, query.plot_id])
        correction.memify_queued = True
        await db.commit()
    except Exception as exc:
        log.error("correction.queue_failed", correction_id=correction.id, error=str(exc))
        correction.memify_queued = False

    # Invalidate query cache so future queries reflect the correction
    n_invalidated = await invalidate_query_cache(td.farm_id)
    log.info(
        "correction.submitted",
        correction_id=correction.id,
        edge_id=body.evidence_edge_id,
        user=td.user_id,
        cache_keys_invalidated=n_invalidated,
    )

    return correction


@router.get("/", response_model=list[CorrectionRead])
async def list_corrections(
    td: TokenData = Depends(require_role("admin", "agronomist")),
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(Correction)
        .join(EvidenceEdge, EvidenceEdge.id == Correction.evidence_edge_id)
        .join(EvidenceEdge.query)
        .where(QueryLog.farm_id == td.farm_id)
        .order_by(Correction.created_at.desc())  # type: ignore[attr-defined]
        .limit(100)
    )
    return result.scalars().all()


@router.post("/{correction_id}/confirm-edge")
async def confirm_causal_edge(
    correction_id: str,
    td: TokenData = Depends(require_role("admin", "agronomist")),
    db: AsyncSession = Depends(get_db),
):
    """
    An agronomist explicitly confirms that an edge represents a confirmed cause.
    This promotes the Neo4j edge to CONFIRMED_CAUSE type (the only way this
    edge type is ever asserted — never auto-generated by the LLM).
    """
    result = await db.execute(
        select(Correction, EvidenceEdge, QueryLog)
        .join(EvidenceEdge, EvidenceEdge.id == Correction.evidence_edge_id)
        .join(QueryLog, QueryLog.id == EvidenceEdge.query_id)
        .where(Correction.id == correction_id, QueryLog.farm_id == td.farm_id)
    )
    row = result.one_or_none()
    if not row:
        raise HTTPException(status_code=404, detail="Correction not found")

    correction, edge, query = row
    if query.plot_id is None or not edge.target_graph_node_id:
        raise HTTPException(status_code=409, detail="This evidence does not include both graph endpoints, so it cannot be confirmed.")
    updated = await mark_edge_confirmed(
        source_id=edge.graph_node_id,
        target_id=edge.target_graph_node_id,
        rel_type=edge.relationship_type,
        confirmed_by=td.user_id,
        farm_id=td.farm_id,
        plot_id=query.plot_id,
    )
    if not updated:
        raise HTTPException(status_code=409, detail="The scoped correlation edge was not found or was already confirmed.")
    await invalidate_query_cache(td.farm_id)
    log.info("correction.edge_confirmed", edge_id=edge.id, agronomist=td.user_id)
    return {"detail": "Edge confirmed as causal", "edge_id": edge.id, "correction_id": correction.id}


@router.post("/trigger-memify", status_code=202)
async def trigger_memify(
    td: TokenData = Depends(require_role("admin")),
    db: AsyncSession = Depends(get_db),
):
    """Retry saved corrections that were not queued successfully."""
    result = await db.execute(
        select(Correction, QueryLog)
        .join(EvidenceEdge, EvidenceEdge.id == Correction.evidence_edge_id)
        .join(QueryLog, QueryLog.id == EvidenceEdge.query_id)
        .where(QueryLog.farm_id == td.farm_id, Correction.memify_queued.is_(False))
        .order_by(Correction.created_at.asc())
        .limit(100)
    )
    queued = 0
    for correction, query in result.all():
        if query.plot_id is None:
            continue
        try:
            memify_correction.apply_async(args=[correction.id, td.farm_id, query.plot_id])
            correction.memify_queued = True
            queued += 1
        except Exception as exc:
            log.error("correction.queue_failed", correction_id=correction.id, error=str(exc))
    await db.commit()
    return {"queued": queued}
