// Generated by scripts/generate_sample_documents.py. All values are fictional.
import type { Document, GraphNode } from "../types/index";

export interface SampleDocument {
  id: string;
  plot_id: string;
  filename: string;
  label: string;
  date: string;
  type: GraphNode["type"];
  entity_label: string;
  properties: GraphNode["properties"];
}

export const sampleDocuments: SampleDocument[] = [
  {
    "id": "sample-a-soil",
    "plot_id": "plot-A",
    "filename": "synthetic-field-a-soil.csv",
    "label": "Synthetic sample — Field A — Soil survey",
    "date": "2026-02-12",
    "type": "Practice",
    "entity_label": "Soil survey (sample)",
    "properties": {
      "synthetic": true,
      "sample_points": 3,
      "description": "Synthetic soil survey observations"
    }
  },
  {
    "id": "sample-a-crop",
    "plot_id": "plot-A",
    "filename": "synthetic-field-a-crop.csv",
    "label": "Synthetic sample — Field A — Crop establishment",
    "date": "2026-03-18",
    "type": "CropVariant",
    "entity_label": "Crop establishment (sample)",
    "properties": {
      "synthetic": true,
      "crop": "Winter Wheat"
    }
  },
  {
    "id": "sample-a-inputs",
    "plot_id": "plot-A",
    "filename": "synthetic-field-a-inputs.csv",
    "label": "Synthetic sample — Field A — Input application records",
    "date": "2026-05-15",
    "type": "ChemicalProduct",
    "entity_label": "Input application records (sample)",
    "properties": {
      "synthetic": true,
      "description": "Fictional input log; not an application recommendation",
      "entries": 3
    }
  },
  {
    "id": "sample-a-weather",
    "plot_id": "plot-A",
    "filename": "synthetic-field-a-weather.csv",
    "label": "Synthetic sample — Field A — Weather observations",
    "date": "2026-09-01",
    "type": "WeatherEvent",
    "entity_label": "Weather observations (sample)",
    "properties": {
      "synthetic": true,
      "months_recorded": 9,
      "description": "Synthetic monthly observations; no causal inference"
    }
  },
  {
    "id": "sample-a-irrigation",
    "plot_id": "plot-A",
    "filename": "synthetic-field-a-irrigation.csv",
    "label": "Synthetic sample — Field A — Irrigation log",
    "date": "2026-08-20",
    "type": "Practice",
    "entity_label": "Irrigation log (sample)",
    "properties": {
      "synthetic": true,
      "events": 5,
      "method": "Example drip irrigation"
    }
  },
  {
    "id": "sample-a-yield",
    "plot_id": "plot-A",
    "filename": "synthetic-field-a-yield.csv",
    "label": "Synthetic sample — Field A — Yield history",
    "date": "2026-09-20",
    "type": "YieldMeasurement",
    "entity_label": "Yield history (sample)",
    "properties": {
      "synthetic": true,
      "value_t_ha": 5.2,
      "years_recorded": 3
    }
  },
  {
    "id": "sample-b-soil",
    "plot_id": "plot-B",
    "filename": "synthetic-field-b-soil.csv",
    "label": "Synthetic sample — Field B — Soil survey",
    "date": "2026-02-12",
    "type": "Practice",
    "entity_label": "Soil survey (sample)",
    "properties": {
      "synthetic": true,
      "sample_points": 3,
      "description": "Synthetic soil survey observations"
    }
  },
  {
    "id": "sample-b-crop",
    "plot_id": "plot-B",
    "filename": "synthetic-field-b-crop.csv",
    "label": "Synthetic sample — Field B — Crop establishment",
    "date": "2026-03-18",
    "type": "CropVariant",
    "entity_label": "Crop establishment (sample)",
    "properties": {
      "synthetic": true,
      "crop": "Corn"
    }
  },
  {
    "id": "sample-b-inputs",
    "plot_id": "plot-B",
    "filename": "synthetic-field-b-inputs.csv",
    "label": "Synthetic sample — Field B — Input application records",
    "date": "2026-05-15",
    "type": "ChemicalProduct",
    "entity_label": "Input application records (sample)",
    "properties": {
      "synthetic": true,
      "description": "Fictional input log; not an application recommendation",
      "entries": 3
    }
  },
  {
    "id": "sample-b-weather",
    "plot_id": "plot-B",
    "filename": "synthetic-field-b-weather.csv",
    "label": "Synthetic sample — Field B — Weather observations",
    "date": "2026-09-01",
    "type": "WeatherEvent",
    "entity_label": "Weather observations (sample)",
    "properties": {
      "synthetic": true,
      "months_recorded": 9,
      "description": "Synthetic monthly observations; no causal inference"
    }
  },
  {
    "id": "sample-b-irrigation",
    "plot_id": "plot-B",
    "filename": "synthetic-field-b-irrigation.csv",
    "label": "Synthetic sample — Field B — Irrigation log",
    "date": "2026-08-20",
    "type": "Practice",
    "entity_label": "Irrigation log (sample)",
    "properties": {
      "synthetic": true,
      "events": 5,
      "method": "Example drip irrigation"
    }
  },
  {
    "id": "sample-b-yield",
    "plot_id": "plot-B",
    "filename": "synthetic-field-b-yield.csv",
    "label": "Synthetic sample — Field B — Yield history",
    "date": "2026-09-20",
    "type": "YieldMeasurement",
    "entity_label": "Yield history (sample)",
    "properties": {
      "synthetic": true,
      "value_t_ha": 7.9,
      "years_recorded": 3
    }
  },
  {
    "id": "sample-c-soil",
    "plot_id": "plot-C",
    "filename": "synthetic-field-c-soil.csv",
    "label": "Synthetic sample — Field C — Soil survey",
    "date": "2026-02-12",
    "type": "Practice",
    "entity_label": "Soil survey (sample)",
    "properties": {
      "synthetic": true,
      "sample_points": 3,
      "description": "Synthetic soil survey observations"
    }
  },
  {
    "id": "sample-c-crop",
    "plot_id": "plot-C",
    "filename": "synthetic-field-c-crop.csv",
    "label": "Synthetic sample — Field C — Crop establishment",
    "date": "2026-03-18",
    "type": "CropVariant",
    "entity_label": "Crop establishment (sample)",
    "properties": {
      "synthetic": true,
      "crop": "Soybean"
    }
  },
  {
    "id": "sample-c-inputs",
    "plot_id": "plot-C",
    "filename": "synthetic-field-c-inputs.csv",
    "label": "Synthetic sample — Field C — Input application records",
    "date": "2026-05-15",
    "type": "ChemicalProduct",
    "entity_label": "Input application records (sample)",
    "properties": {
      "synthetic": true,
      "description": "Fictional input log; not an application recommendation",
      "entries": 3
    }
  },
  {
    "id": "sample-c-weather",
    "plot_id": "plot-C",
    "filename": "synthetic-field-c-weather.csv",
    "label": "Synthetic sample — Field C — Weather observations",
    "date": "2026-09-01",
    "type": "WeatherEvent",
    "entity_label": "Weather observations (sample)",
    "properties": {
      "synthetic": true,
      "months_recorded": 9,
      "description": "Synthetic monthly observations; no causal inference"
    }
  },
  {
    "id": "sample-c-irrigation",
    "plot_id": "plot-C",
    "filename": "synthetic-field-c-irrigation.csv",
    "label": "Synthetic sample — Field C — Irrigation log",
    "date": "2026-08-20",
    "type": "Practice",
    "entity_label": "Irrigation log (sample)",
    "properties": {
      "synthetic": true,
      "events": 5,
      "method": "Example drip irrigation"
    }
  },
  {
    "id": "sample-c-yield",
    "plot_id": "plot-C",
    "filename": "synthetic-field-c-yield.csv",
    "label": "Synthetic sample — Field C — Yield history",
    "date": "2026-09-20",
    "type": "YieldMeasurement",
    "entity_label": "Yield history (sample)",
    "properties": {
      "synthetic": true,
      "value_t_ha": 3.0,
      "years_recorded": 3
    }
  }
];

export const sampleDemoDocuments: Document[] = sampleDocuments.map(sample => ({
  id: sample.id, plot_id: sample.plot_id, source_type: "csv", label: sample.label,
  storage_uri: `/sample-documents/${sample.filename}`, ingest_status: "ready",
  source_confidence: 1, uploaded_at: "2026-09-30T09:00:00Z", date_of_event: sample.date,
}));
