"""Rebuild the deterministic, explicitly synthetic CSV examples shipped with the app."""
import csv
import io
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEST = ROOT / 'frontend/public/sample-documents'
DEST.mkdir(parents=True, exist_ok=True)
catalog = []
for index, (field, crop, base_yield) in enumerate([('A', 'Winter Wheat', 5.4), ('B', 'Corn', 8.1), ('C', 'Soybean', 3.2)]):
    examples = [
        ('soil', 'Soil survey', 'Practice', '2026-02-12', ['date', 'sample_point', 'ph', 'organic_matter_pct'],
         [['2026-02-12', point, round(6.1 + index * .2 + n * .1, 1), round(2.5 + n * .2, 1)] for n, point in enumerate(['north', 'centre', 'south'])],
         {'sample_points': 3, 'description': 'Synthetic soil survey observations'}),
        ('crop', 'Crop establishment', 'CropVariant', '2026-03-18', ['date', 'crop', 'activity', 'area_ha'],
         [['2026-03-18', crop, 'Sowing recorded', [42.5, 38.2, 29.1][index]]], {'crop': crop}),
        ('inputs', 'Input application records', 'ChemicalProduct', '2026-05-15', ['date', 'product', 'recorded_amount', 'unit'],
         [['2026-03-20', 'Example fertiliser A', 85 + index * 5, 'kg/ha'], ['2026-04-18', 'Example compost', 1.8 + index * .2, 't/ha'], ['2026-05-15', 'Example fertiliser B', 40 + index * 3, 'kg/ha']],
         {'description': 'Fictional input log; not an application recommendation', 'entries': 3}),
        ('weather', 'Weather observations', 'WeatherEvent', '2026-09-01', ['date', 'rainfall_mm', 'mean_temperature_c'],
         [[f'2026-{month:02}-01', max(8, 68 - month * 5 + index * 8), 9 + month * 2 - index] for month in range(1, 10)],
         {'months_recorded': 9, 'description': 'Synthetic monthly observations; no causal inference'}),
        ('irrigation', 'Irrigation log', 'Practice', '2026-08-20', ['date', 'applied_water_mm', 'method'],
         [[f'2026-{month:02}-20', 20 + index * 4, 'Example drip irrigation'] for month in range(4, 9)],
         {'events': 5, 'method': 'Example drip irrigation'}),
        ('yield', 'Yield history', 'YieldMeasurement', '2026-09-20', ['date', 'crop', 'yield_t_ha'],
         [[f'{year}-09-20', crop, round(base_yield + delta, 2)] for year, delta in [(2024, .1), (2025, .3), (2026, -.2)]],
         {'value_t_ha': round(base_yield - .2, 2), 'years_recorded': 3}),
    ]
    for kind, title, node_type, event_date, columns, rows, properties in examples:
        filename = f'synthetic-field-{field.lower()}-{kind}.csv'
        stream = io.StringIO(newline='')
        writer = csv.writer(stream)
        writer.writerow(['data_origin', 'sample_field', *columns])
        writer.writerows([['SYNTHETIC_DEMO_NOT_REAL_FARM_DATA', f'Field {field}', *row] for row in rows])
        (DEST / filename).write_text(stream.getvalue(), encoding='utf-8')
        catalog.append({'id': f'sample-{field.lower()}-{kind}', 'plot_id': f'plot-{field}', 'filename': filename,
                        'label': f'Synthetic sample — Field {field} — {title}', 'date': event_date,
                        'type': node_type, 'entity_label': f'{title} (sample)', 'properties': {'synthetic': True, **properties}})
header = '''// Generated by scripts/generate_sample_documents.py. All values are fictional.
import type { Document, GraphNode } from "../types/index";

export interface SampleDocument {
  id: string;
  plot_id: string;
  filename: string;
  label: string;
  date: string;
  type: GraphNode["type"];
  entity_label: string;
  properties: GraphNode["properties"];
}

export const sampleDocuments: SampleDocument[] = '''
footer = ''';

export const sampleDemoDocuments: Document[] = sampleDocuments.map(sample => ({
  id: sample.id, plot_id: sample.plot_id, source_type: "csv", label: sample.label,
  storage_uri: `/sample-documents/${sample.filename}`, ingest_status: "ready",
  source_confidence: 1, uploaded_at: "2026-09-30T09:00:00Z", date_of_event: sample.date,
}));
'''
(ROOT / 'frontend/src/data/sample-documents.ts').write_text(header + json.dumps(catalog, indent=2, ensure_ascii=False) + footer, encoding='utf-8')
(DEST / 'README.md').write_text('''# Synthetic field document pack

18 CSV documents: six each for the wheat, corn, and soybean demo fields.
Each field includes soil observations, crop establishment, input applications,
weather observations, irrigation events, and three years of yields (24 rows per field).
All measurements, dates, products, and field names are fictional examples.
Every CSV row carries SYNTHETIC_DEMO_NOT_REAL_FARM_DATA. These are not agronomic recommendations.

Open the local demo to see these records and their graph connections automatically.
In a signed-in workspace, Ingest & Review offers a sample pack selector and an
Import button. That action uploads six CSVs to the selected real field through the
normal authenticated ingestion flow. Duplicate content is deduplicated per field.
Samples remain labeled as synthetic. Processing requires the configured backend,
storage, worker, and model services. A saved record is not a verified agronomic claim.

Regenerate with python scripts/generate_sample_documents.py.
''', encoding='utf-8')
print(f'Generated {len(catalog)} synthetic documents')
